memory_limit=256M
max_execution_time=300
max_input_vars=10000
max_file_uploads=100
post_max_size=128M
upload_max_filesize=128M
date.timezone=Europe/Moscow

display_errors=On
display_startup_errors=On
error_reporting=E_ALL

realpath_cache_size=4096K
opcache.enable=1
opcache.revalidate_freq=0
opcache.validate_timestamps=1

openssl.cafile=/etc/ssl/certs/ca-certificates.crt
curl.cainfo=/etc/ssl/certs/ca-certificates.crt